# Generated by Django 4.2 on 2023-05-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='warehouse_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.warehouseitem'),
        ),
    ]
